<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function searchByName($name)
    {
        
        /** Doctrine Query Language */
        // return $this->getEntityManager()
        //     ->createQuery(
        //         'SELECT p FROM AppBundle:Product p WHERE p.name LIKE :name'
        //     )
        //     ->setParameter('name', "%$name%")
        //     ->getResult();

        /** Doctrine Query Builder **/
        return $this->createQueryBuilder('p')
        ->where("p.name LIKE :name")
        ->setParameter('name', "%$name%")
        ->getQuery()
        ->getResult();
    }
}
